import type { Metadata } from "next";
import "./globals.css";
import localFont from "next/font/local";

const SUIT = localFont({
  src: [
    { path: "./font/SUIT-Regular.ttf", weight: "400", style: "normal" },
    { path: "./font/SUIT-SemiBold.ttf", weight: "600", style: "normal" },
    { path: "./font/SUIT-Bold.ttf", weight: "700", style: "normal" },
  ],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko" className={SUIT.className}>
      <body>{children}</body>
    </html>
  );
}
